## Put this in config/santoku-config.yml

hipchat:
    token: "your_hipchat_api_token"
    room: "developers"
    from: "Knife"
    notify: false
    color:  "yellow"
campfire:
    subdomain: "mycampfiredomain"
    token: "your_campfire_api_token"
    room: "developers"
    notify: false
